### ISSUE TITLE
UTF-8 harvesting issue with OAI-PMH targets

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#108]
Some of the data that is harvested via OAI-PMH mangles the diactrics. We need to find out if this is caused by setting at the provider end or if this is issue in the Narthex harvesting->source pipe-line. 

I will provide a sample dataset and target urls to reproduce this issue to the developer that picks this up directly.

**Comment by hanswesterbeek** [comment]
Said endpoint returns following http-response:
```
HTTP/1.1 200 OK
CONTENT-TYPE: Text/XML
CONTENT-LENGTH: 3378
```

This is obviously wrong.

It should be: `Content-Type: text/xml; charset=utf-8`

Having said that, I guess the chances of those people fixing this are near to zero so I'll see what I can do.

**Comment by hanswesterbeek** [comment]
Won't fix.
