### ISSUE TITLE
max allowed upload size too low.

### ISSUE THREAD

**Issue by zemyatin** [delving/narthex#120]
Currently only 50mb max allowed. Raw XML often exceeds that by far.

**Comment by zemyatin** [comment]
Check if narthex angular is using multi-part file upload

**Comment by hanswesterbeek** [comment]
@zemyatin This is a setting in the application .conf file and in the nginx settings. 
P/m me an example of where this goes wrong and I'll verify. Closing this issue for now and will re-open
