### ISSUE TITLE
Adlib harvesting preview is not routing to the right link

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#121]
The preview button in the dataset view for the adlib harvesting is currently using the same parameters as OAI-PMH to construct the URL. This leads to an error on the Adlib API. This URL needs to be structured the same way as we do to build the harvest URL.

**Comment by hanswesterbeek** [comment]
@kiivihal is this what you have a local branch for?

**Comment by kiivihal** [comment]
@hanswesterbeek Yes that is correct. There is a pull-request here for you: https://github.com/delving/narthex/pull/126

**Comment by hanswesterbeek** [comment]
Fixed in 0.4.3
