### ISSUE TITLE
TripleStore parameters for different actions need to be configurable. 

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#122]
Currently, narthex supports Apache Fuseki as TripleStore back-end. We are also moving towards supporting BlazeGraph. Although the triplestore base url can be configured the parameters (/update, /sparql, /query, /data) are hard-coded. Blazegraph uses '/sparql' for each of these parameters to access Query, Update and GraphStore protocol functionality. So the cleanest way to deal with this is to make these parameters configuration options that Narthex picks up when it constructs the URLs.

**Comment by hanswesterbeek** [comment]
Let's discuss Blazegraph migration as a seperate topic sometime soon. Until then, I don't think it is a good idea to make any code modifications anticipating such a migration.
