### ISSUE TITLE
Filtering in Narthex doesn't work properly since the deployment of v0.4.3.

### ISSUE THREAD

**Issue by ceeejeee** [delving/narthex#139]
It seems that you can now filter only by dataset Name and not by Spec anymore.

http://data.brabantcloud.nl/narthex/#/dataset-list

![schermafbeelding 2016-11-10 om 11 46 01](https://cloud.githubusercontent.com/assets/18716083/20173868/806d4552-a73b-11e6-8adb-5cd273066658.png)

**Comment by hanswesterbeek** [comment]
I am inclined to remove this feature altogether and simply sort alphabetically by specname. 

@kiivihal what do you think?

**Comment by hanswesterbeek** [comment]
Removed this functionality as it is non essentials and we have bigger fish to fry.
