### ISSUE TITLE
Admin account not useable if no fuseki present at startup

### ISSUE THREAD

**Issue by jaclu** [delving/narthex#142]
If fuseki is not running or is wrongly configured and narthex fails to set the admin password at startup. No indication is given in the web interface that the admin account is not present/might be out of date. 
(This remains true even if fuseki is correctly started after Narthex was started.)

This makes it is rather unintuitive when you get login failed in narthex.
Ideally display a warning/error something like "Failed to verify admin account during startup"

**Comment by hanswesterbeek** [comment]
This reminds of the Nave/django discussion we had earlier.

I guess the correct way forward is that:
1. Narthex reports to be in 'unhealthy' state when it can not verify that that an admin account exists
2. Logs on ERROR level when this occurs at startup

**Comment by hanswesterbeek** [comment]
Added the ability to monitor the app, at `/non-public/monitoring/health`for two things:

 1. Does the admin-user exist?
 2. Is Fuseki responding with a configurable amount of time?

Configure the required timeout (your criteria for considering the app 'healthy') in `narthex.conf`:
```
healthchecks {
  fuseki.timeoutMillis = 100
}
```

Sample unhealthy output:

```json
{
  "admin-user-exists" : {
    "healthy" : false,
    "message" : "Could not reach underlying store within 100 milliseconds. Exception: java.net.ConnectException: Connection refused: localhost/fe80:0:0:0:0:0:0:1%1:3030",
    "error" : null
  },
  "fuseki" : {
    "healthy" : false,
    "message" : "Could not reach underlying store within 100 milliseconds. Exception: java.net.ConnectException: Connection refused: localhost/fe80:0:0:0:0:0:0:1%1:3030",
    "error" : null
  }
}
```

Sample healthy output:
```json
{
  "admin-user-exists" : {
    "healthy" : true,
    "message" : null,
    "error" : null
  },
  "fuseki" : {
    "healthy" : true,
    "message" : "Responded within 100 milliseconds",
    "error" : null
  }
}
```
