### ISSUE TITLE
Websocket timeout NGINX

### ISSUE THREAD

**Issue by geralddejong** [delving/narthex#55]
NGINX standard configuration for web sockets terminates the connection after one minute. They recommend a heartbeat send from the application to keep the connection open. See and . Also make sure for testing that you are running Nginx 1.3.13 or later. Some of the issues described below continue to exist when you interact with Narthex directly to its own port.

**Comment by kiivihal** [comment]
This has been fixed in the upgrade to play 2.4.x Also NGINX has been upgraded and the configuration now has the proper websocket settings. These templates are managed through the Fabric and Ansible provisioning scripts.
