### ISSUE TITLE
SIP-Creator Connect

### ISSUE THREAD

**Issue by geralddejong** [delving/narthex#58]
Sip-Creator throws error messages on first connect but then connect fine on second or third try. This is very confusing for the end-user.

**Comment by kiivihal** [comment]
This seems to be related to how sessions are started by Play. On the second request the session has been established and you can connect. 

So this issue should be solved in either the client (sip-creator) or in the authentication endpoint.

**Comment by hanswesterbeek** [comment]
Seems to me this kind of connection should be stateless, but that's too big of a change for now.

I will open a issue to that effect over at sip-creator.
