### ISSUE TITLE
 Set the initial Narthex admin password on startup when none exists

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/narthex#73]
On deployments, the password should be set as part of the ansible playbook. The point is that there must not be a manual extra step to do it during development.

When it is first set, it should not be touched afterwards, so whatever the user changes it to, must not be overwritten by a playbook

Fixed by #71

**Comment by jaclu** [comment]
Implemented in our ansible deploys, and tested on both vagrant and cloud server deploys
