### ISSUE TITLE
Saving records to a MessageQueue

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#76]
Currently, Narthex saves to an Nave endpoint for indexing the aggregated records. This design requires both Narthex and Nave to share information and authentication. It might be better to save the EDM/RDF records directly to a MessageQueue like kafka and have Nave just consume the records from the same queue. 

Currently, the following information is added into the JSON message are:
- verb = the action that needs to be performed ('clear_orphans', 'disable_index', 'drop_dataset', 'index' (= default action))
- dataset = dataset spec
- graph = actual RDF triples
- graphUri = the named graph of the RDF triples
- contentHash = the contenthash of the RDF triples serialized in RDF/XML format

Possible issue to keep in mind are:
- when the saving process is interrupted the already saved messages should be erased from the queue
- the current switch between NaveBulkApi boolean setting needs to be preserved, but renamed to something like save via MessageQueue. When this setting is false it needs to keep storing the records directly to the TripleStore.

**Comment by hanswesterbeek** [comment]
It is not sufficiently clear to me which big problem would be solved by doing this. In turn, I can imagine a few new problems we would get from doing this.

If configuration is the only issue, as "... requires both Narthex and Nave to share information and authentication" seems to suggest, then I don't think this would be worthwhile.
