### ISSUE TITLE
Current emailing implementation has non-12factor behaviour

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/narthex#78]
The check for 'playMode == prod' should be removed. Instead, sent messages should be labeled with the environment they were sent from so users can:

1. Receive and test messages in every environment
2. Adapt their email-client filters to only really pay attention to 'production' emails. 

This will only affect people involved with development/testing of the application.

**Comment by jaclu** [comment]
Nave uses getsentry/raven for bug notifications, this saves a lot of hassle not having to setup smtp on every server, the bane of using cloud servers in a world where most smtp servers are paranoid and refuses to receive mail from servers not using the organisations default mx.
Not sure if getsentry/raven is available for Scala, but a quick google found a getsentry/raven-java repo on github, that might be useful.

**Comment by hanswesterbeek** [comment]
@jaclu You are confusing this operational issue with the actual feature of emailing process-reports to end-users that narthex has.

FYI, v0.3.7 has getsentry enabled, up to you to configure it.

**Comment by hanswesterbeek** [comment]
Fixed.
