### ISSUE TITLE
Theseaurus skos xml file size not loading

### ISSUE THREAD

**Issue by zemyatin** [delving/narthex#85]
On the SKOS Vocabularies view a user cannot drop/upload a file larger than aprox. 10MB to create a new SKOS vocabulary/thesaurus

The latest version of the Erfgoed Thesaurus xml is 17.6 MB. Somewhere in the configuration for nginx(?) the max upload size needs to allow for files of this size or larger.

Also (after locally trimming the file to get passed the file size limit) another error arose. This was due to the fact that the Erfgoed Thesaurus xml file contained namespaces (dcterms in this case) which were not declared in the xml opening. The attached file does have this namespace added. Unzip and use containing xml file for debugging.
[erfgoed_thesaurus_2015-09-28.xml.zip](https://github.com/delving/narthex/files/432021/erfgoed_thesaurus_2015-09-28.xml.zip)

**Comment by hanswesterbeek** [comment]
@kiivihal Do you think there should be a max-size at all? What would the consequences of not having one be?

**Comment by hanswesterbeek** [comment]
This file has the namespaces all fixed....
[erfgoed_thesaurus_2015-09-28_with_all_namespaces.xml.gz](https://github.com/delving/narthex/files/432870/erfgoed_thesaurus_2015-09-28_with_all_namespaces.xml.gz)
