### ISSUE TITLE
Be a better netizen when harvesting

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/narthex#90]
Currently, when 'harvesting' large numbers of datasets, the application is known to flood upstream servers with a lot of concurrent requests. This issue is further compounded by the fact that some clients have many datasets which they want to update every 5 minutes.

So, lots of harvesting occurs, all the time.

A solution would:
- Randomize the t=0 for each interval, to decrease 'burst overload'-behaviour
- limit the amount of concurrent requests per upstream server

**Comment by hanswesterbeek** [comment]
Perhaps throttle the harvester with this: http://doc.akka.io/docs/akka/snapshot/contrib/throttle.html

**Comment by zemyatin** [comment]
Perhaps we should be a little more strict in the minimum increment time. Every five minutes seems to me to be very often... if these are datasets whose information is going to save lives, then yes, every five minutes, but it's cultural heritage data, and no one's life depends on it. So perhaps we should set a minimum of 1 hour.

**Comment by hanswesterbeek** [comment]
Also, I think we need a number from the Memorix people. What is the max amount of concurrent requests they are willing to accept?

**Comment by hanswesterbeek** [comment]
@zemyatin yes i agree that we should allow at most every hour. I'll open an issue for that separately.

**Comment by hanswesterbeek** [comment]
This is sufficiently addressed by limiting both the amount of concurrent harvests and the minimun interval used by any harvest.
