### ISSUE TITLE
Thesaurus mapping times out on SPARQL query 

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#91]
When the thesaurus mapping interface is loaded and a thesaurus is selected, you will get a network timeout. 

Reproduction steps:

* load the test dataset
* go through all steps until save
* go to explore
* skosify a field (preferably material or technique)
* go back to dataset overview page
* if no thesaurus/vocabulary is loaded, load a SKOS vocabulary like the "erfgoed thesaurus"
* go to 'Map vocabulary terms'
* then select the "erfgoed thesaurus"
* wait for the time-out

The application currently does the following things:

* load the whole SKOS vocabulary from the Fuseki Triple store 
* convert it to JSON
* make it available via an API call to Angular
* load it in browser memory so that it can be queried for the duration of the Thesaurus mapping session 

Once it is reproduced we should also look into how the actual sparql query can be optimized so only the required information is returned from the triple-store.

**Comment by hanswesterbeek** [comment]
[erfgoed_thesaurus_2015-09-28_with_all_namespaces.xml.gz](https://github.com/delving/narthex/files/466838/erfgoed_thesaurus_2015-09-28_with_all_namespaces.xml.gz)

**Comment by hanswesterbeek** [comment]
I've tried to reproduce this but I do get to these screens:

![screen shot 2016-09-12 at 12 00 12 pm](https://cloud.githubusercontent.com/assets/233545/18432105/972190ac-78e0-11e6-9f8a-2d0156b2ed62.png)
![screen shot 2016-09-12 at 12 00 31 pm](https://cloud.githubusercontent.com/assets/233545/18432107/98f46cf6-78e0-11e6-9e00-38e24d58d5e2.png)

So the error does not occur for me?

**Comment by hanswesterbeek** [comment]
Actually mapping works as well
![screen shot 2016-09-12 at 12 19 34 pm](https://cloud.githubusercontent.com/assets/233545/18432612/38dc36e8-78e3-11e6-85ed-561943d662a1.png)

**Comment by kiivihal** [comment]
I am no longer able to reproduce this in develop or acceptance environment. The very specific problem that we still have must be related to the deployment.
