### ISSUE TITLE
LocalId part of the hubId should not contain a colon (":")

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#93]
Further downstream at indexing time, ElasticSearch replaces a ":" with "-" when indexing doc_ids. Since we allow the colon to be part of the hubId this causes some unexpected behaviour. Nave, will in the next release, already replace ":" with "-". 

It makes sense if Narthex enforces the same rules. In the PocketParser.scala there is already some efforts to create cleanIds but here is a lot of code duplication. It would be best if a cleanId function would do this in a single place.

This is the code from nave that creates the clean_id:

```python
local_id = raw_id.replace("_", "-").replace(":", "-").replace(" ", "-").replace("+", "-").replace("/", "-")
        if "--" in local_id:
            local_id = re.sub("[-]{2,10}", "-", local_id)

```

**Comment by hanswesterbeek** [comment]
Fixed by PR #94
